from web3 import Web3
from web3.types import Address, ChecksumAddress, ENS
from web3.contract import Contract
from typing import Union

ABI = [{'inputs': [{'internalType': 'uint256[4]',
              'name': 'input',
              'type': 'uint256[4]'}],
  'name': 'BNAddFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'bytes', 'name': 'dst', 'type': 'bytes'}],
  'name': 'InvalidDSTLength',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'x', 'type': 'uint256'}],
  'name': 'InvalidFieldElement',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'noSqrt', 'type': 'uint256'}],
  'name': 'MapToPointFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'base', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'exponent', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'modulus', 'type': 'uint256'}],
  'name': 'ModExpFailed',
  'type': 'error'},
 {'anonymous': False,
  'inputs': [{'indexed': False,
              'internalType': 'bytes',
              'name': 'calculatedPayload',
              'type': 'bytes'}],
  'name': 'DebugPayload',
  'type': 'event'},
 {'anonymous': False,
  'inputs': [{'indexed': False,
              'internalType': 'string',
              'name': 'agentDID',
              'type': 'string'},
             {'indexed': False,
              'internalType': 'string',
              'name': 'actionIdentifier',
              'type': 'string'},
             {'indexed': False,
              'internalType': 'string',
              'name': 'resourceIdentifier',
              'type': 'string'},
             {'indexed': False,
              'internalType': 'uint256',
              'name': 'expiry',
              'type': 'uint256'}],
  'name': 'TokenIssued',
  'type': 'event'},
 {'inputs': [{'internalType': 'string', 'name': 'agentDID', 'type': 'string'},
             {'internalType': 'string',
              'name': 'resourceIdentifier',
              'type': 'string'},
             {'internalType': 'string',
              'name': 'actionIdentifier',
              'type': 'string'}],
  'name': 'evaluate',
  'outputs': [{'components': [{'internalType': 'string',
                               'name': 'agentDID',
                               'type': 'string'},
                              {'internalType': 'string',
                               'name': 'actionIdentifier',
                               'type': 'string'},
                              {'internalType': 'string',
                               'name': 'resourceIdentifier',
                               'type': 'string'},
                              {'internalType': 'uint256',
                               'name': 'expiry',
                               'type': 'uint256'}],
               'internalType': 'struct IACC.AccessToken',
               'name': 'token',
               'type': 'tuple'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'string',
              'name': 'resourceIdentifier',
              'type': 'string'},
             {'internalType': 'string',
              'name': 'actionIdentifier',
              'type': 'string'}],
  'name': 'getPolicy',
  'outputs': [{'components': [{'internalType': 'enum IACC.PolicyType',
                               'name': 'policyType',
                               'type': 'uint8'},
                              {'internalType': 'bytes',
                               'name': 'policyParameters',
                               'type': 'bytes'}],
               'internalType': 'struct IACC.Policy[]',
               'name': '',
               'type': 'tuple[]'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'components': [{'internalType': 'string',
                              'name': 'agentDID',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'actionIdentifier',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'resourceIdentifier',
                              'type': 'string'},
                             {'internalType': 'uint256',
                              'name': 'expiry',
                              'type': 'uint256'}],
              'internalType': 'struct IACC.AccessToken',
              'name': 'token',
              'type': 'tuple'}],
  'name': 'getTokenHash',
  'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
  'stateMutability': 'pure',
  'type': 'function'},
 {'inputs': [{'components': [{'internalType': 'string',
                              'name': 'resourceIdentifier',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'actionIdentifier',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'policyTypeStr',
                              'type': 'string'},
                             {'components': [{'internalType': 'string',
                                              'name': 'key',
                                              'type': 'string'},
                                             {'internalType': 'string',
                                              'name': 'value',
                                              'type': 'string'}],
                              'internalType': 'struct IACC.KV[]',
                              'name': 'policyParameters',
                              'type': 'tuple[]'},
                             {'internalType': 'uint8',
                              'name': 'requiredSigs',
                              'type': 'uint8'},
                             {'internalType': 'uint256[2]',
                              'name': 'aggSig',
                              'type': 'uint256[2]'},
                             {'internalType': 'uint8',
                              'name': 'pksMask',
                              'type': 'uint8'}],
              'internalType': 'struct IACC.RegisterPolicyParams',
              'name': 'params',
              'type': 'tuple'}],
  'name': 'registerPolicy',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'components': [{'internalType': 'string',
                              'name': 'resourceIdentifier',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'actionIdentifier',
                              'type': 'string'},
                             {'internalType': 'string',
                              'name': 'policyTypeStr',
                              'type': 'string'},
                             {'components': [{'internalType': 'string',
                                              'name': 'key',
                                              'type': 'string'},
                                             {'internalType': 'string',
                                              'name': 'value',
                                              'type': 'string'}],
                              'internalType': 'struct IACC.KV[]',
                              'name': 'policyParameters',
                              'type': 'tuple[]'},
                             {'internalType': 'uint256[2]',
                              'name': 'aggSig',
                              'type': 'uint256[2]'},
                             {'internalType': 'uint8',
                              'name': 'pksMask',
                              'type': 'uint8'}],
              'internalType': 'struct IACC.RemovePolicyParams',
              'name': 'params',
              'type': 'tuple'}],
  'name': 'removePolicy',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [],
  'name': 'systemThreatLevel',
  'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes32',
              'name': 'tokenHash',
              'type': 'bytes32'}],
  'name': 'verifyTokenHash',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'stateMutability': 'view',
  'type': 'function'}]

def get_contract(
    w3: Web3,
    address: Union[Address, ChecksumAddress, ENS],
) -> Contract:
    """
    Returns a Web3.py Contract instance for `AccessControlContract`.
    """
    return w3.eth.contract(address=address, abi=ABI)
