from web3 import Web3
from web3.types import Address, ChecksumAddress, ENS
from web3.contract import Contract
from typing import Union

ABI = [{'inputs': [{'internalType': 'uint256[4]',
              'name': 'input',
              'type': 'uint256[4]'}],
  'name': 'BNAddFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'bytes', 'name': 'dst', 'type': 'bytes'}],
  'name': 'InvalidDSTLength',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'x', 'type': 'uint256'}],
  'name': 'InvalidFieldElement',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'noSqrt', 'type': 'uint256'}],
  'name': 'MapToPointFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'base', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'exponent', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'modulus', 'type': 'uint256'}],
  'name': 'ModExpFailed',
  'type': 'error'},
 {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'string',
              'name': 'DID',
              'type': 'string'},
             {'indexed': True,
              'internalType': 'bytes32',
              'name': 'documentHash',
              'type': 'bytes32'},
             {'indexed': False,
              'internalType': 'address[]',
              'name': 'controllers',
              'type': 'address[]'}],
  'name': 'DIDCreated',
  'type': 'event'},
 {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'string',
              'name': 'DID',
              'type': 'string'},
             {'indexed': True,
              'internalType': 'bytes32',
              'name': 'newDocumentHash',
              'type': 'bytes32'}],
  'name': 'DIDDocumentUpdated',
  'type': 'event'},
 {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'string',
              'name': 'DID',
              'type': 'string'}],
  'name': 'DIDRevoked',
  'type': 'event'},
 {'inputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'name': 'nonces',
  'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'string', 'name': 'DID', 'type': 'string'},
             {'internalType': 'bytes32',
              'name': 'documentHash',
              'type': 'bytes32'},
             {'internalType': 'address[]',
              'name': 'controllers',
              'type': 'address[]'},
             {'internalType': 'uint256[4][]',
              'name': 'blsPubKeys',
              'type': 'uint256[4][]'},
             {'internalType': 'uint8',
              'name': '_requiredSigsForCapUpdate',
              'type': 'uint8'}],
  'name': 'register',
  'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'string', 'name': 'DID', 'type': 'string'}],
  'name': 'resolve',
  'outputs': [{'internalType': 'bytes32',
               'name': 'documentHash',
               'type': 'bytes32'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'string', 'name': 'DID', 'type': 'string'},
             {'internalType': 'uint256[2]',
              'name': 'aggSig',
              'type': 'uint256[2]'},
             {'internalType': 'uint256',
              'name': 'controllerMask',
              'type': 'uint256'}],
  'name': 'revoke',
  'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'string', 'name': 'DID', 'type': 'string'},
             {'internalType': 'bytes32',
              'name': 'newDocumentHash',
              'type': 'bytes32'},
             {'internalType': 'uint256[2]',
              'name': 'aggSig',
              'type': 'uint256[2]'},
             {'internalType': 'uint256',
              'name': 'controllerMask',
              'type': 'uint256'}],
  'name': 'update',
  'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'}],
  'stateMutability': 'nonpayable',
  'type': 'function'}]

def get_contract(
    w3: Web3,
    address: Union[Address, ChecksumAddress, ENS],
) -> Contract:
    """
    Returns a Web3.py Contract instance for `AgentGovernanceContract`.
    """
    return w3.eth.contract(address=address, abi=ABI)
