from web3 import Web3
from web3.types import Address, ChecksumAddress, ENS
from web3.contract import Contract
from typing import Union

ABI = [{'inputs': [{'internalType': 'uint256[4]',
              'name': 'input',
              'type': 'uint256[4]'}],
  'name': 'BNAddFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'bytes', 'name': 'dst', 'type': 'bytes'}],
  'name': 'InvalidDSTLength',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'x', 'type': 'uint256'}],
  'name': 'InvalidFieldElement',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'noSqrt', 'type': 'uint256'}],
  'name': 'MapToPointFailed',
  'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'base', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'exponent', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'modulus', 'type': 'uint256'}],
  'name': 'ModExpFailed',
  'type': 'error'},
 {'anonymous': False,
  'inputs': [{'indexed': False,
              'internalType': 'bytes32',
              'name': 'dataHash',
              'type': 'bytes32'},
             {'indexed': False,
              'internalType': 'string',
              'name': 'cid',
              'type': 'string'},
             {'indexed': False,
              'internalType': 'uint256',
              'name': 'expiry',
              'type': 'uint256'},
             {'indexed': False,
              'internalType': 'string',
              'name': 'status',
              'type': 'string'}],
  'name': 'DataAnchored',
  'type': 'event'},
 {'anonymous': False,
  'inputs': [{'indexed': False,
              'internalType': 'bytes32',
              'name': 'dataHash',
              'type': 'bytes32'},
             {'indexed': False,
              'internalType': 'string',
              'name': 'newStatus',
              'type': 'string'}],
  'name': 'DataUpdated',
  'type': 'event'},
 {'inputs': [{'internalType': 'bytes32', 'name': 'dataHash', 'type': 'bytes32'},
             {'internalType': 'string', 'name': 'cid', 'type': 'string'},
             {'internalType': 'uint256', 'name': 'expiry', 'type': 'uint256'},
             {'internalType': 'string', 'name': 'status', 'type': 'string'}],
  'name': 'anchor',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes32',
              'name': 'dataHash',
              'type': 'bytes32'}],
  'name': 'get',
  'outputs': [{'internalType': 'bytes32',
               'name': 'dataHash_',
               'type': 'bytes32'},
              {'internalType': 'string', 'name': 'cid_', 'type': 'string'},
              {'internalType': 'uint256', 'name': 'expiry_', 'type': 'uint256'},
              {'internalType': 'string', 'name': 'status_', 'type': 'string'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'uint256[2]',
              'name': 'aggSig',
              'type': 'uint256[2]'},
             {'internalType': 'bytes32', 'name': 'dataHash', 'type': 'bytes32'},
             {'internalType': 'string', 'name': 'milestone', 'type': 'string'},
             {'internalType': 'string[]', 'name': 'dids', 'type': 'string[]'},
             {'internalType': 'uint8', 'name': 'pksMask', 'type': 'uint8'}],
  'name': 'update',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'}]

def get_contract(
    w3: Web3,
    address: Union[Address, ChecksumAddress, ENS],
) -> Contract:
    """
    Returns a Web3.py Contract instance for `DataAnchoringContract`.
    """
    return w3.eth.contract(address=address, abi=ABI)
